s = set()
n=input("enter your number :")
s.add(int(n))
n=input("enter your number :")
s.add(int(n))
n=input("enter your number :")
s.add(int(n))
n=input("enter your number :")
s.add(int(n))
n=input("enter your number :")
s.add(int(n))
n=input("enter your number :")
s.add(int(n))
n=input("enter your number :")
s.add(int(n))
n=input("enter your number :")
s.add(int(n))
print(s)